apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-asset
  namespace: default
  labels:
    app: calculator-asset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-asset
  template:
    metadata:
      labels:
        app: calculator-asset
    spec:
      containers:
        - name: calculator-asset
          image: amoldeshpande/calculator-v1:latest
          ports:
            - containerPort: 8080
# http://169.51.206.174:30440/